# Generated by Django 3.1 on 2020-12-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200828_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='in_post_image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='in_post_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='in_post_video',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
