# Generated by Django 3.1 on 2020-12-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201211_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='in_post_subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='in_post_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
